<?php
require_once('tcpdf/tcpdf.php');

// Extend the TCPDF class to create custom Header and Footer
class SalesReportPDF extends TCPDF {

    //Page header
    public function Header() {
        // Logo
        $image_file = K_PATH_IMAGES.'3GMED.jpg';
        
        // Calculate X position to center the image
        $pageWidth = $this->getPageWidth();
        $imageWidth = 100; // Adjust as needed
        $xPos = ($pageWidth - $imageWidth) / 2;

        $this->Image($image_file, $xPos, 10, 100, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        
        // Calculate X positions to center the line
        $lineStartX = $xPos - 90;
        $lineEndX = $xPos + 190; // Adjust line length as needed

        // Draw a line below the logo
        $this->Line($lineStartX, 75, $lineEndX, 75); // Adjust Y position to move the line below the logo

        // Set font
        $this->SetFont('times', 'B', 30);
        
        // Add Sales Report text
        $this->SetY(40); // Adjust the Y position as needed
        $this->Cell(0, 90, 'Sales Report', 0, false, 'C', 0, '', 0, false, 'T', 'M');
        
        // Move Y position below the text
        $this->SetY(80); // Adjust the Y position based on your requirements
    }

//Page footer
public function Footer() {
    // Set Y position at 15 mm from bottom
    $this->SetY(-15);
    // Set font
    $this->SetFont('helvetica', 'I', 8);
    $this->Cell(0, 10, 'Generated by: Admin ', 0, false, 'L', 0, '', 0, false, 'T', 'M');
    // Set timezone to Asia/Manila
    date_default_timezone_set('Asia/Manila');
    // Right side: Date and time in Philippine time format
    $this->Cell(0, 10, 'Generated on: ' . date('Y-m-d h:i A'), 0, false, 'R', 0, '', 0, false, 'T', 'M');
}
}

// Create new PDF document
$pdf = new SalesReportPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Sales Report');
$pdf->SetSubject('Sales Report');
$pdf->SetKeywords('TCPDF, PDF, sales, report');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 100, PDF_MARGIN_RIGHT); // Increased top margin to accommodate the header

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// Fetch data from the database
$connection = mysqli_connect("localhost", "root", "", "dbpharmacy");

// Get filtered data if provided
$selected_start_date = isset($_GET['start_date']) ? $_GET['start_date'] : '';
$selected_end_date = isset($_GET['end_date']) ? $_GET['end_date'] : '';
$selected_assistant = isset($_GET['pharmacy_assistant']) ? $_GET['pharmacy_assistant'] : '';
$selected_branch = isset($_GET['branch']) ? $_GET['branch'] : '';

// Construct the WHERE clause for the SQL query
$where_clause = '';
if (!empty($selected_start_date) && !empty($selected_end_date)) {
    $where_clause .= " WHERE date BETWEEN '$selected_start_date' AND '$selected_end_date'";
}
if (!empty($selected_assistant) && $selected_assistant !== 'Select Name') {
    if (!empty($where_clause)) {
        $where_clause .= " AND";
    } else {
        $where_clause .= " WHERE";
    }
    $where_clause .= " cashier_name = '$selected_assistant'";
}
if (!empty($selected_branch)) {
    if (!empty($where_clause)) {
        $where_clause .= " AND";
    } else {
        $where_clause .= " WHERE";
    }
    $where_clause .= " branch = '$selected_branch'";
}

// Query to fetch sales data
$query = "SELECT date, cashier_name, branch, SUM(total_amount) AS day_total FROM transaction_list" . $where_clause . " GROUP BY date, cashier_name, branch ORDER BY date ASC";
$result = mysqli_query($connection, $query);

// Initialize variables
$total_earnings = 0;

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 10);

// Calculate table width
$tableWidth = $pdf->getPageWidth() - $pdf->getMargins()['left'] - $pdf->getMargins()['right'];

// Set table header
$pdf->SetY(100);
$pdf->SetFillColor(37, 158, 158); // Change the fill color to #259E9E
$pdf->SetTextColor(255);

$pdf->SetX(($pdf->getPageWidth() - $tableWidth) / 2); // Center the table horizontally

if (!empty($selected_branch)) {
    $pdf->Cell($tableWidth * 0.2, 8, 'Branch', 1, 0, 'C', 1);
}
if (!empty($selected_assistant) && $selected_assistant !== 'Select Name') {
    $pdf->Cell($tableWidth * 0.3, 8, 'Pharmacy Assistant', 1, 0, 'C', 1);
}
if (!empty($selected_start_date) && !empty($selected_end_date)) {
    $pdf->Cell($tableWidth * 0.2, 8, 'Date', 1, 0, 'C', 1);
}
$pdf->Cell($tableWidth * 0.2, 8, 'Earnings', 1, 1, 'C', 1);

// Data rows
$pdf->SetFillColor(255);
$pdf->SetTextColor(0);

$pdf->SetX(($pdf->getPageWidth() - $tableWidth) / 2); // Center the table horizontally

while ($row = mysqli_fetch_assoc($result)) {
    if (!empty($selected_branch)) {
        $pdf->Cell($tableWidth * 0.2, 8, $row['branch'], 1, 0, 'C', false);
    }
    if (!empty($selected_assistant) && $selected_assistant !== 'Select Name') {
        $pdf->Cell($tableWidth * 0.3, 8, $row['cashier_name'], 1, 0, 'C', false);
    }
    if (!empty($selected_start_date) && !empty($selected_end_date)) {
        $pdf->Cell($tableWidth * 0.2, 8, $row['date'], 1, 0, 'C', false);
    }
    $pdf->Cell($tableWidth * 0.2, 8, $row['day_total'], 1, 1, 'C', false);
    
    $total_earnings += $row['day_total']; // Increment total earnings
    $pdf->SetX(($pdf->getPageWidth() - $tableWidth) / 2); // Center the table horizontally
}

// Display total earnings
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell($tableWidth * 0.8, 8, 'Total Earnings', 1, 0, 'R', true); 
$pdf->Cell($tableWidth * 0.2, 8, number_format($total_earnings, 2, '.', ''), 1, 1, 'C', true);
$pdf->SetX(($pdf->getPageWidth() - $tableWidth) / 2); // Center the table horizontally

// Close and output PDF document
$pdf->Output('sales_report.pdf', 'I');

// Close database connection
mysqli_close($connection);
?>
