<?php
require_once('tcpdf/tcpdf.php');

// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

    // Page header
    public function Header() {
        // Logo
        $image_file = K_PATH_IMAGES.'3GMED.jpg';
        
        // Calculate X position to center the image
        $pageWidth = $this->getPageWidth();
        $imageWidth = 100; // Adjust as needed
        $xPos = ($pageWidth - $imageWidth) / 2;

        $this->Image($image_file, $xPos, 10, 100, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        
        // Calculate X positions to center the line
        $lineStartX = $xPos - 90;
        $lineEndX = $xPos + 190; // Adjust line length as needed

        // Draw a line below the logo
        $this->Line($lineStartX, 75, $lineEndX, 75); // Adjust Y position to move the line below the logo

        // Set font
        $this->SetFont('times', 'B', 30);
        
        // Add Inventory Reports text
        $this->SetY(40); // Adjust the Y position as needed
        $this->Cell(0, 90, 'Inventory Report', 0, false, 'C', 0, '', 0, false, 'T', 'M');
        
        // Move Y position below the text
        $this->SetY(100); // Adjust the Y position based on your requirements
    }

//Page footer
public function Footer() {
    // Set Y position at 15 mm from bottom
    $this->SetY(-15);
    // Set font
    $this->SetFont('helvetica', 'I', 8);
    $this->Cell(0, 10, 'Generated by: Admin ', 0, false, 'L', 0, '', 0, false, 'T', 'M');
    // Set timezone to Asia/Manila
    date_default_timezone_set('Asia/Manila');
    // Right side: Date and time in Philippine time format
    $this->Cell(0, 10, 'Generated on: ' . date('Y-m-d h:i A'), 0, false, 'R', 0, '', 0, false, 'T', 'M');
}
}

// Create new PDF document
$pdf = new MYPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Nicola Asuni');
$pdf->SetTitle('Inventory Report');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 100, PDF_MARGIN_RIGHT); // Increased top margin to accommodate the header

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// Fetch data from the database
$connection = mysqli_connect("localhost", "root", "", "dbpharmacy");
// Filter branch
$selectedBranch = isset($_GET['branch']) ? $_GET['branch'] : 'All';

$query = "SELECT * FROM add_stock_list";
if ($selectedBranch !== 'All') {
    $query .= " WHERE branch = '$selectedBranch'";
}
$query .= " ORDER BY id DESC"; // Sort by ID column in descending order
$result = mysqli_query($connection, $query);

// Initialize max widths array
$maxWidth = array(10, 31, 30, 30, 20, 20, 24, 30, 26, 26);

// Calculate the maximum width needed for each column based on the content
while ($row = mysqli_fetch_assoc($result)) {
    $maxWidth[0] = max($maxWidth[0], $pdf->GetStringWidth($row['id']) + 5); // Adjust cell width
    $maxWidth[1] = max($maxWidth[1], $pdf->GetStringWidth($row['sku']) + 5); // Adjusted width for SKU
    $maxWidth[2] = max($maxWidth[2], $pdf->GetStringWidth($row['product_stock_name']) + 5);
    $maxWidth[3] = max($maxWidth[3], $pdf->GetStringWidth($row['descript']) + 5);
    $maxWidth[4] = max($maxWidth[4], $pdf->GetStringWidth($row['quantity']) + 5); // Adjust cell width
    $maxWidth[5] = max($maxWidth[5], $pdf->GetStringWidth($row['price']) + 5);
    $maxWidth[6] = max($maxWidth[6], $pdf->GetStringWidth($row['branch']) + 5);
    $maxWidth[7] = max($maxWidth[7], $pdf->GetStringWidth($row['batch_number']) + 5); // Adjust cell width
    $maxWidth[8] = max($maxWidth[8], $pdf->GetStringWidth($row['expiry_date']) + 5);
    $maxWidth[9] = max($maxWidth[9], $pdf->GetStringWidth($row['date_added']) + 5);
}

// Add a page
$pdf->AddPage();

// Set font for the table headers
$pdf->SetFont('helvetica', 'B', 11);

// Set fill color for header row
$pdf->SetFillColor(48, 75, 27);
$pdf->SetTextColor(255);

// Calculate X position to center the table headers
$headerXPos = ($pdf->getPageWidth() - array_sum($maxWidth)) / 2;

$pdf->SetX($headerXPos); // Set X position to center the table headers

// Header row
$pdf->Cell($maxWidth[0], 8, 'ID', 1, 0, 'C', 1); // Adjust cell width
$pdf->Cell($maxWidth[1], 8, 'SKU', 1, 0, 'C', 1); // Adjusted width for SKU
$pdf->Cell($maxWidth[2], 8, 'Product Name', 1, 0, 'C', 1);
$pdf->Cell($maxWidth[3], 8, 'Description', 1, 0, 'C', 1);
$pdf->Cell($maxWidth[4], 8, 'Quantity', 1, 0, 'C', 1); // Adjust cell width
$pdf->Cell($maxWidth[5], 8, 'Price', 1, 0, 'C', 1);
$pdf->Cell($maxWidth[6], 8, 'Branch', 1, 0, 'C', 1);
$pdf->Cell($maxWidth[7], 8, 'Batch Number', 1, 0, 'C', 1); // Adjust cell width
$pdf->Cell($maxWidth[8], 8, 'Expiry Date', 1, 0, 'C', 1);
$pdf->Cell($maxWidth[9], 8, 'Date Added', 1, 1, 'C', 1);

// Set font for the table data
$pdf->SetFont('helvetica', '', 10);
$pdf->SetTextColor(0);

// Calculate X position to center the table data
$dataXPos = $headerXPos; // Adjusted for the width of the table

$pdf->SetX($dataXPos); // Set X position to center the table data

// Data rows
$fill = false;
mysqli_data_seek($result, 0); // Reset the result pointer to start
while ($row = mysqli_fetch_assoc($result)) {
    $pdf->Cell($maxWidth[0], 8, $row['id'], 1, 0, 'C', $fill); // Adjust cell width
    $pdf->Cell($maxWidth[1], 8, $row['sku'], 1, 0, 'C', $fill); // Adjusted width for SKU
    $pdf->Cell($maxWidth[2], 8, $row['product_stock_name'], 1, 0, 'C', $fill);
    $pdf->Cell($maxWidth[3], 8, $row['descript'], 1, 0, 'C', $fill);
    $pdf->Cell($maxWidth[4], 8, $row['quantity'], 1, 0, 'C', $fill); // Adjust cell width
    $pdf->Cell($maxWidth[5], 8, $row['price'], 1, 0, 'C', $fill);
    $pdf->Cell($maxWidth[6], 8, $row['branch'], 1, 0, 'C', $fill);
    $pdf->Cell($maxWidth[7], 8, $row['batch_number'], 1, 0, 'C', $fill); // Adjust cell width
    $pdf->Cell($maxWidth[8], 8, $row['expiry_date'], 1, 0, 'C', $fill);
    $pdf->Cell($maxWidth[9], 8, $row['date_added'], 1, 1, 'C', $fill);
    $pdf->SetX($dataXPos); // Set X position to center the table data
}

// Close database connection
mysqli_close($connection);

// Close and output PDF document
$pdf->Output('stocks_report.pdf', 'I');
?>
